<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>hdl-labs-parent</artifactId>
        <groupId>com.hdl.springboot.labs</groupId>
        <version>1.0-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>labx-08-spring-cloud-gateway</artifactId>
    <packaging>pom</packaging>
    <modules>
        <module>labx-08-sc-gateway-static</module>
        <module>labx-08-sc-gateway-registry</module>
        <module>labx-08-sc-gateway-rate-limit</module>
    </modules>

</project>