spring:
  config:
    import:
      - nacos:demo-application.yaml?group=DEFAULT_GROUP&refreshEnabled=true
  cloud:
    nacos:
      username: nacos
      password: nacos
      config:
        server-addr: 127.0.0.1:8848
        namespace: REPLACE_ME_PROD_NAMESPACE_ID