server:
  port: 8082

spring:
  application:
    name: demo-consumer-discovery
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 127.0.0.1:8848
        ip: 127.0.0.1
        service: ${spring.application.name}